services:
  postgres:
    image: postgres:16-alpine
    container_name: cyberaudit-db
    environment:
      POSTGRES_DB: cyberaudit
      POSTGRES_USER: cyberaudit
      POSTGRES_PASSWORD: cyberaudit123
    ports:
      - "5432:5432"
    volumes:
      - cyberaudit_data:/var/lib/postgresql/data

volumes:
  cyberaudit_data: