server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5434/cyberaudit
spring.datasource.username=cyberaudit
spring.datasource.password=cyberaudit123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.info.env.enabled=false