package com.joao.cyberaudit.model;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_2FA_VERIFIED,
    SCAN_STARTED,
    SCAN_COMPLETED,
    DOMAIN_ADDED,
    DOMAIN_VERIFIED,
    DOMAIN_REMOVED,
    USER_INVITED,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    TOTP_ENABLED,
    TOTP_DISABLED,
    EMAIL_OTP_ENABLED,
    EMAIL_OTP_DISABLED,
    REQUIRE_2FA_CHANGED,
    DATA_EXPORTED,
    ACCOUNT_DELETED,
    API_KEY_CREATED,
    API_KEY_REVOKED
}
